package com.gmq.psp.soap.manageschool;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-23T18:44:56.998+01:00
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "ManageSchool",
                  wsdlLocation = "file:/C:/Users/alexg/Desktop/sometihng/Servers/WebContent/WSDL/manageSchool.wsdl",
                  targetNamespace = "http://www.example.org/manageSchool/")
public class ManageSchool_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/manageSchool/", "ManageSchool");
    public final static QName ManageSchoolSOAP = new QName("http://www.example.org/manageSchool/", "ManageSchoolSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/alexg/Desktop/sometihng/Servers/WebContent/WSDL/manageSchool.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ManageSchool_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/alexg/Desktop/sometihng/Servers/WebContent/WSDL/manageSchool.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ManageSchool_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ManageSchool_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageSchool_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ManageSchool_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ManageSchool_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ManageSchool_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ManageSchool
     */
    @WebEndpoint(name = "ManageSchoolSOAP")
    public ManageSchool getManageSchoolSOAP() {
        return super.getPort(ManageSchoolSOAP, ManageSchool.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageSchool
     */
    @WebEndpoint(name = "ManageSchoolSOAP")
    public ManageSchool getManageSchoolSOAP(WebServiceFeature... features) {
        return super.getPort(ManageSchoolSOAP, ManageSchool.class, features);
    }

}
