package com.gmq.psp.soap.manageschool;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-23T18:44:56.983+01:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://www.example.org/manageSchool/", name = "ManageSchool")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ManageSchool {

    @WebMethod(operationName = "ManageAsignature", action = "http://www.example.org/manageSchool/ManageAsignature")
    @WebResult(name = "AsignatureResponse", targetNamespace = "http://www.example.org/manageSchool/", partName = "AsignatureStatus")
    public AsignatureResponse manageAsignature(

        @WebParam(partName = "objAsignature", name = "AsignatureRequest", targetNamespace = "http://www.example.org/manageSchool/")
        AsignatureRequest objAsignature
    );

    @WebMethod(operationName = "ManageEvalation", action = "http://www.example.org/manageSchool/ManageStudent")
    @WebResult(name = "EvaluationResponse", targetNamespace = "http://www.example.org/manageSchool/", partName = "EvaluationStatus")
    public EvaluationResponse manageEvalation(

        @WebParam(partName = "objEvaluation", name = "EvaluationRequest", targetNamespace = "http://www.example.org/manageSchool/")
        EvaluationRequest objEvaluation
    );

    @WebMethod(operationName = "ManageStudent", action = "http://www.example.org/manageSchool/ManageStudent")
    @WebResult(name = "StudentResponse", targetNamespace = "http://www.example.org/manageSchool/", partName = "StudentStatus")
    public StudentResponse manageStudent(

        @WebParam(partName = "ObjStudent", name = "StudentRequest", targetNamespace = "http://www.example.org/manageSchool/")
        StudentRequest objStudent
    );
}
