
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.gmq.psp.soap.manageschool;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-23T18:44:56.942+01:00
 * Generated source version: 3.3.5
 *
 */

@javax.jws.WebService(
                      serviceName = "ManageSchool",
                      portName = "ManageSchoolSOAP",
                      targetNamespace = "http://www.example.org/manageSchool/",
                      wsdlLocation = "file:/C:/Users/alexg/Desktop/sometihng/Servers/WebContent/WSDL/manageSchool.wsdl",
                      endpointInterface = "com.gmq.psp.soap.manageschool.ManageSchool")

public class ManageSchoolSOAPImpl implements ManageSchool {

    private static final Logger LOG = Logger.getLogger(ManageSchoolSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see com.gmq.psp.soap.manageschool.ManageSchool#manageAsignature(com.gmq.psp.soap.manageschool.AsignatureRequest objAsignature)*
     */
    public com.gmq.psp.soap.manageschool.AsignatureResponse manageAsignature(AsignatureRequest objAsignature) {
        LOG.info("Executing operation manageAsignature");
        System.out.println(objAsignature);
        try {
            com.gmq.psp.soap.manageschool.AsignatureResponse _return = new com.gmq.psp.soap.manageschool.AsignatureResponse();
            _return.setStatus("Status-1602962377");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gmq.psp.soap.manageschool.ManageSchool#manageEvalation(com.gmq.psp.soap.manageschool.EvaluationRequest objEvaluation)*
     */
    public com.gmq.psp.soap.manageschool.EvaluationResponse manageEvalation(EvaluationRequest objEvaluation) {
        LOG.info("Executing operation manageEvalation");
        System.out.println(objEvaluation);
        try {
            com.gmq.psp.soap.manageschool.EvaluationResponse _return = new com.gmq.psp.soap.manageschool.EvaluationResponse();
            _return.setStatus("Status-536983629");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.gmq.psp.soap.manageschool.ManageSchool#manageStudent(com.gmq.psp.soap.manageschool.StudentRequest objStudent)*
     */
    public com.gmq.psp.soap.manageschool.StudentResponse manageStudent(StudentRequest objStudent) {
        LOG.info("Executing operation manageStudent");
        System.out.println(objStudent);
        try {
            com.gmq.psp.soap.manageschool.StudentResponse _return = new com.gmq.psp.soap.manageschool.StudentResponse();
            _return.setStatus("Status-1216051298");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
